### PR TITLE
New version; try to rerender

### PR DESCRIPTION
**Pull request by emthompson-usgs**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
We need https://github.com/conda-forge/staged-recipes/pull/21198 first

**Comment by ocefpaf** [comment]
The pyproject.toml requires `setuptools-scm >=6.3.2` to run but I'm almost certain that is a build time dependency requirement only. It also asks for cython at build time but I did not see any compiled extension and this can probably be noarch.

**Comment by emthompson-usgs** [comment]
@ocefpaf Thanks, the cython thing is a remnant from before we moved the c code to a dependency, and setuptools-scm is just my own ignorance. I'll make these changes to the branch.

**Comment by emthompson-usgs** [comment]
Actually, I can't find where it is asking for cython. Can you clarify?

**Comment by ocefpaf** [comment]
> @ocefpaf Thanks, the cython thing is a remnant from before we moved the c code to a dependency, and setuptools-scm is just my own ignorance. I'll make these changes to the branch.

No problem. Normal when we re-factor big things. I just wanted to be sure before sending a PR here. The `esi-*` packages should be in the channel soon and this PR will probably pass when they do.

**Comment by emthompson-usgs** [comment]
Maybe this is a difference in what branch we are talking about. I was looking in emthompson-usgs:v1.2.2, while the recipe in main does request cython.

**Comment by emthompson-usgs** [comment]
Okay, I removed setuptools-scm from the recipe for this commit. I also fixed it and the cython dependency in pyproject.toml, but if the issue is not breaking anything I'd prefer to just let that change take effect on the next release rather than making a new release just for this change.

**Comment by ocefpaf** [comment]
> Okay, I removed setuptools-scm from the recipe for this commit. I also fixed it and the cython dependency in pyproject.toml, but if the issue is not breaking anything I'd prefer to just let that change take effect on the next release rather than making a new release just for this change.

We don't need to change anything in this PR now. Specially if we want to try pip-check. However, I'm almost sure that won't pass b/c of some naming issues (beautifulsoup4 vs bs4) but skipping pip-check is not a big deal.

**Comment by emthompson-usgs** [comment]
Is there a way to make this build noarch in the recipe? I don't know what is currently triggering the separate builds.

**Comment by ocefpaf** [comment]
> Is there a way to make this build noarch in the recipe? I don't know what is currently triggering the separate builds.

I converted it in the last commits. All you need is to declare `noarch: python` and re-render.

**Comment by emthompson-usgs** [comment]
> I converted it in the last commits. All you need is to declare `noarch: python` and re-render.

Got it. Thanks so much for all the help getting this package to build!

**Pull request merged**
