### PR TITLE
Update to v1.1.0

### PR DESCRIPTION
**Pull request by emthompson-usgs**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by emthompson-usgs** [comment]
@conda-forge-admin, please rerender

**Comment by emthompson-usgs** [comment]
@mhearne-usgs Can you look at this? This seems to be an issue with the wrong compiler getting installed (or different than what the build script is expecting) in the linux builds. This is the relevant portion of the docker log:
```
  creating build/temp.linux-x86_64-3.6/gmprocess
  creating build/temp.linux-x86_64-3.6/gmprocess/metrics
  clang -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/gmprocess_1598804790600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/gmprocess_1598804790600/work=/usr/local/src/conda/gmprocess-1.1.0 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/gmprocess_1598804790600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p=/usr/local/src/conda-prefix -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/conda/feedstock_root/build_artifacts/gmprocess_1598804790600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/include -fPIC -Igmprocess/metrics -I/home/conda/feedstock_root/build_artifacts/gmprocess_1598804790600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6/site-packages/numpy/core/include -I/home/conda/feedstock_root/build_artifacts/gmprocess_1598804790600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/include/python3.6m -c gmprocess/metrics/oscillators.c -o build/temp.linux-x86_64-3.6/gmprocess/metrics/oscillators.o
  unable to execute 'clang': No such file or directory
  error: command 'clang' failed with exit status 1
  Building wheel for gmprocess (setup.py): finished with status 'error'
```

The only thing we do currently to specify the c compiler in the recipe.yml is:
```
  build:
    - {{ compiler('c') }}
```
I've been looking for documentation on this, but I can't find any info on this type of error or how to specify different c compilers (e.g., clang vs gcc).

**Comment by emthompson-usgs** [comment]
Also, note that it seems like it has to be something specific to the conda forge build process because [our CI builds](https://github.com/usgs/groundmotion-processing/pull/536) were successful.

**Comment by mhearne-usgs** [comment]
@conda-forge-admin, please update for conda-build 3

**Comment by mhearne-usgs** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
